[package]
org = "ballerinax"
name = "health.clients.hl7"
version = "2.0.1"
distribution = "2201.12.3"
authors = ["Ballerina"]
keywords = ["Area/Healthcare", "Industry/Healthcare", "Type/Connector", "HL7", "HL7V2"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-health.clients"
readme = "Package.md"

[build-options]
observabilityIncluded = true
