[package]
org = "ballerinax"
name = "health.clients.fhir"
version = "3.0.1"
distribution = "2201.12.3"
authors = ["Ballerina"]
keywords = ["Area/Healthcare", "Industry/Healthcare", "Type/Connector", "FHIR", "R4"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-health.clients"

[build-options]
observabilityIncluded = true
