[package]
org = "ballerinax"
name = "health.clients.fhir.epic"
version = "1.0.1"
distribution = "2201.12.9"
#visibility = "private"
icon = "./icons/Icon_Epic.png"
keywords=["Area/Healthcare", "Industry/Healthcare", "Type/Connector", "Vendor/Epic", "Epic FHIR Connector"]
